### ISSUE TITLE
Performance of your solution

### ISSUE THREAD

**Issue by MBurtsev** [VSadov/NonBlocking#6]
Hi, I have thoroughly tested the performance of your solution. It really turned out that in single-threaded mode your solution runs 25% faster. However, if you add new threads, your code starts to degrade in time and eventually starts to lose 2 times when 12 thread. At this time, the standard code looks stable regardless of the number of threads. In the tests, I measured the time of adding 10,000,000 elements using the **TryAdd** method.

> **System.Collections.Concurrent.ConcurrentDictionary:**
> ConcurrentDictionary 01 threads, median time - 3966
> ConcurrentDictionary 02 threads, median time - 4871
> ConcurrentDictionary 03 threads, median time - 4657
> ConcurrentDictionary 04 threads, median time - 4514
> ConcurrentDictionary 05 threads, median time - 5227
> ConcurrentDictionary 06 threads, median time - 4898
> ConcurrentDictionary 07 threads, median time - 5424
> ConcurrentDictionary 08 threads, median time - 4906
> ConcurrentDictionary 09 threads, median time - 5293
> ConcurrentDictionary 10 threads, median time - 4811
> ConcurrentDictionary 11 threads, median time - 4960
> ConcurrentDictionary 12 threads, median time - 4859

> **NonBlocking.ConcurrentDictionary:**
> ConcurrentDictionary 01 threads, median time - 2880
> ConcurrentDictionary 02 threads, median time - 4361
> ConcurrentDictionary 03 threads, median time - 5846
> ConcurrentDictionary 04 threads, median time - 6215
> ConcurrentDictionary 05 threads, median time - 6559
> ConcurrentDictionary 06 threads, median time - 6683
> ConcurrentDictionary 07 threads, median time - 6845
> ConcurrentDictionary 08 threads, median time - 7147
> ConcurrentDictionary 09 threads, median time - 7498
> ConcurrentDictionary 10 threads, median time - 8097
> ConcurrentDictionary 11 threads, median time - 8478
> ConcurrentDictionary 12 threads, median time - 8806

**Comment by MBurtsev** [comment]
And even when you do tests, you must make sure that the threads start at the same time, for this you can use the simple method.

 ```
       void DoWork(...)
        {
           // ...
            Interlocked.Add(ref ready, 1);

            while(Thread.VolatileRead(ref ready)< works.Count)
            {
            }
           // ... begin test here
       }
```

**Comment by MBurtsev** [comment]
In addition, running tests with tasks is not a good idea. Since the task manager does not allocate threads  immediately, it has a cunning algorithm. Therefore, for such tests it is better to use one of two designs.

```
            // start test with threads
            for (var i = 0; i < works.Count; ++i)
            {
                var itm = works[i];

                new Thread(() => DoWork(itm).Start();
            }

            // setup pool
            ThreadPool.SetMaxThreads(100, 200);
            // ....

            // start test with pool
            for (var i = 0; i < works.Count; ++i)
            {
                var itm = works[i];

                ThreadPool.QueueUserWorkItem(state => DoWork(itm), null);
            }
```

**Comment by VSadov** [comment]
Sorry for not looking at this earlier. I has been a long time since I touched this project. 

I am wondering - is there a chance to get the code sample that demonstrates the differences?
If there is an issue, how can I reproduce it?

Thanks!

**Comment by MBurtsev** [comment]
You can get the right benchmarks [from here](https://github.com/MBurtsev/MBur.ConcurrentDictionary). Insert your class there to see the objective data.

**Comment by cata02** [comment]
@VSadov any reason not to have this (or other lock-free) implementation replace the concurrent dict in .net core?

**Comment by MBurtsev** [comment]
@cata02 Intolerable Bureaucracy at Microsoft :).

**Comment by jmarolf** [comment]
@cata02 both the implementation in this repo and others have different runtime behavior that would cause existing programs to break. I know that improvements here would be happily accepted by the team if they did not break existing programs.

**Comment by VSadov** [comment]
> both the implementation in this repo and others have different runtime behavior that would cause existing programs to break

I do not believe this is true about this implementation. 
@cata02 - is this just an assumption or you know of a particular scenario? Could you give an example?

**Comment by jmarolf** [comment]
> I do not believe this is true about this implementation.

Ah sorry, I seem to remember `Remove` behaving differently in this implementation vs. the .NET one

**Comment by VSadov** [comment]
Yes. Before 1.1 the key remove was done as a part of a resize, which is not guaranteed to happen. If you had an expensive key or relied on its finalization, you could be affected. 

That seems rather uncommon scenario, since noone ever complained, but it was indeed a difference in the behavior.  
Anyways, 1.1 fixed that. There is a guarantee now when the keys of removed entries will be GCd.

**Comment by VSadov** [comment]
> any reason not to have this (or other lock-free) implementation replace the concurrent dict in .net core?

That is not how the question is asked typically. 
For inclusion into FX it would be:
- Is there a need?
- What is the cost?
- What is the risk?

Since this is an actual implementation (not a prototype or proposal), the cost is low. It would be mostly about need vs. risk.

To be honest, I do not think there is a huge need to replace `ConcurrentDictionary`. For many users it is _good enough_ . 
For something running on a 4-core machine and the dictionary not being at the core of the app, there will be no difference.

Those who could really benefit from a replacement can try this one. Nuget makes it very easy. 
Having one in the framework, does not prevent from using another. It is MIT-licensed, you can use it however you want.

I.E. - In my personal projects I do not use `ConcurrentDictionary`, I just use this one. I see very little downside to that. If something happens, I know where to ask for a fix or improvement.

**Comment by cata02** [comment]
@VSadov Seeing msft's good focus on perf these days, not sure this would not benefit the framework.
Also, people might not even be aware that there is a better way that the framework's built-in stuff.

But in the end, if the cost to add it is negligible, a better questions is why not just add it?

Anyway, awesome work!

**Comment by VSadov** [comment]
@cata02  Thanks! I will consider proposing this to include in framework when I am confident this is nearly always a win and there are no corner cases which are yet plausible and can cause bad performance.

This particular issue, for example, worries me. I see different numbers form reported and there are variations between environments and scenarios. There are few regressions that I cannot explain. 
I am not yet sure what causes extra costs for nonblocking scenario - whether it is something in the implementation of the dictionary, in the way the benchmark is implemented and interaction with threading and GC or maybe it is all of the above combined.

**Comment by MBurtsev** [comment]
@VSadov Do you work at Microsoft? Your view of things as a person of large corporation is interesting. Yes, stability and predictability are very important. Such a fundamental thing as a hash-table should be very well verified, because it is used on servers that serve hundreds of billions dollars of business.

**Comment by VSadov** [comment]
I looked into the reported repro in more details. 

First - the benchmark was using the default GC configuration, which is Workstation GC. Workstation GC is optimized for scenarios where most allocations happen on a single thread (that is still very common). Since we are specifically dealing with concurrent scenarios I changed the benchmark to use Server GC.

Even with Server GC there were some regressions compared to ConcurrentDictionary. In particular it was unexpected to see regressions in scenarios that Write/Update. 
One observation was that regressions were in scenarios that are known to allocate. There is probably still something in the benchmark that has bad effects on GC. I suspect that could be the threads that spin-wait for the scenarios to complete. The outer harness (BenchmarkDotNet) runs everything at high priority and spinning threads could starve background GC threads, for example. That is only a theory though, maybe it is something else. 

With assumption that this benchmark penalizes allocations, the actual reason  for Write/Update regression becomes clear. ConcurrentDictionary has a special optimization for cases where values are primitive types which can be written atomically. In such cases ConcurrentDictionary does not need to allocate new nodes when updating values. The benchmark uses `ConcurrentDictionary<int, int>`, which falls into such case. Thus when allocations become expensive, ConcurrentDictionary has extra advantage which is not seen when GC works normally and allocations are cheaper.

This benchmark convinced me that the same allocation-reducing optimizations for primitive values would be good to have in NonBlocking dictionary as well.  

I will consider this issue as an ask for such optimizations.
